name: board_uikit
version: 1.0.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  get: 4.6.6
  icons_plus: ^5.0.0
  flutter_animate: 4.5.0
  get_storage: 2.1.1
  flutter: 
    sdk: flutter
  test: ^1.24.9
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

